//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SelfEvaluation", "CriteriaLevel", "Criteria", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PublicSite.Models.Criterion), "Level", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PublicSite.Models.Level), true)]
[assembly: EdmRelationshipAttribute("SelfEvaluation", "SelectionLevel", "Selection", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PublicSite.Models.Selection), "Level", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PublicSite.Models.Level))]

#endregion

namespace PublicSite.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SelfEvaluationContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SelfEvaluationContainer object using the connection string found in the 'SelfEvaluationContainer' section of the application configuration file.
        /// </summary>
        public SelfEvaluationContainer() : base("name=SelfEvaluationContainer", "SelfEvaluationContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SelfEvaluationContainer object.
        /// </summary>
        public SelfEvaluationContainer(string connectionString) : base(connectionString, "SelfEvaluationContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SelfEvaluationContainer object.
        /// </summary>
        public SelfEvaluationContainer(EntityConnection connection) : base(connection, "SelfEvaluationContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Criterion> Criteria
        {
            get
            {
                if ((_Criteria == null))
                {
                    _Criteria = base.CreateObjectSet<Criterion>("Criteria");
                }
                return _Criteria;
            }
        }
        private ObjectSet<Criterion> _Criteria;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Selection> Selections
        {
            get
            {
                if ((_Selections == null))
                {
                    _Selections = base.CreateObjectSet<Selection>("Selections");
                }
                return _Selections;
            }
        }
        private ObjectSet<Selection> _Selections;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Level> Levels
        {
            get
            {
                if ((_Levels == null))
                {
                    _Levels = base.CreateObjectSet<Level>("Levels");
                }
                return _Levels;
            }
        }
        private ObjectSet<Level> _Levels;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Criteria EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCriteria(Criterion criterion)
        {
            base.AddObject("Criteria", criterion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Selections EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSelections(Selection selection)
        {
            base.AddObject("Selections", selection);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Levels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLevels(Level level)
        {
            base.AddObject("Levels", level);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SelfEvaluation", Name="Criterion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Criterion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Criterion object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="category">Initial value of the Category property.</param>
        /// <param name="identifier">Initial value of the Identifier property.</param>
        public static Criterion CreateCriterion(global::System.Int32 id, global::System.String name, global::System.String category, global::System.String identifier)
        {
            Criterion criterion = new Criterion();
            criterion.Id = id;
            criterion.Name = name;
            criterion.Category = category;
            criterion.Identifier = identifier;
            return criterion;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Identifier
        {
            get
            {
                return _Identifier;
            }
            set
            {
                OnIdentifierChanging(value);
                ReportPropertyChanging("Identifier");
                _Identifier = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Identifier");
                OnIdentifierChanged();
            }
        }
        private global::System.String _Identifier;
        partial void OnIdentifierChanging(global::System.String value);
        partial void OnIdentifierChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SelfEvaluation", "CriteriaLevel", "Level")]
        public EntityCollection<Level> Levels
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Level>("SelfEvaluation.CriteriaLevel", "Level");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Level>("SelfEvaluation.CriteriaLevel", "Level", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SelfEvaluation", Name="Level")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Level : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Level object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="criteriaId">Initial value of the CriteriaId property.</param>
        /// <param name="levelNumber">Initial value of the LevelNumber property.</param>
        public static Level CreateLevel(global::System.Int32 id, global::System.String name, global::System.String description, global::System.Int32 criteriaId, global::System.Int32 levelNumber)
        {
            Level level = new Level();
            level.Id = id;
            level.Name = name;
            level.Description = description;
            level.CriteriaId = criteriaId;
            level.LevelNumber = levelNumber;
            return level;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CriteriaId
        {
            get
            {
                return _CriteriaId;
            }
            set
            {
                OnCriteriaIdChanging(value);
                ReportPropertyChanging("CriteriaId");
                _CriteriaId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CriteriaId");
                OnCriteriaIdChanged();
            }
        }
        private global::System.Int32 _CriteriaId;
        partial void OnCriteriaIdChanging(global::System.Int32 value);
        partial void OnCriteriaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LevelNumber
        {
            get
            {
                return _LevelNumber;
            }
            set
            {
                OnLevelNumberChanging(value);
                ReportPropertyChanging("LevelNumber");
                _LevelNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LevelNumber");
                OnLevelNumberChanged();
            }
        }
        private global::System.Int32 _LevelNumber;
        partial void OnLevelNumberChanging(global::System.Int32 value);
        partial void OnLevelNumberChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SelfEvaluation", "CriteriaLevel", "Criteria")]
        public Criterion Criterion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Criterion>("SelfEvaluation.CriteriaLevel", "Criteria").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Criterion>("SelfEvaluation.CriteriaLevel", "Criteria").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Criterion> CriterionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Criterion>("SelfEvaluation.CriteriaLevel", "Criteria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Criterion>("SelfEvaluation.CriteriaLevel", "Criteria", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SelfEvaluation", "SelectionLevel", "Selection")]
        public EntityCollection<Selection> Selections
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Selection>("SelfEvaluation.SelectionLevel", "Selection");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Selection>("SelfEvaluation.SelectionLevel", "Selection", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SelfEvaluation", Name="Selection")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Selection : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Selection object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Selection CreateSelection(global::System.Int32 id)
        {
            Selection selection = new Selection();
            selection.Id = id;
            return selection;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SelfEvaluation", "SelectionLevel", "Level")]
        public EntityCollection<Level> Levels
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Level>("SelfEvaluation.SelectionLevel", "Level");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Level>("SelfEvaluation.SelectionLevel", "Level", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
